services:
  # MongoDB 資料庫服務
  mongodb:
    image: mongo:7.0
    container_name: sketchfab-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-sketchfab_data}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - sketchfab-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Sketchfab 資料擷取應用程式
  fetch-sketchfab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sketchfab-fetcher
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
      logstash:
        condition: service_healthy
    environment:
      # MongoDB 設定
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-admin123}@mongodb:27017/${MONGODB_DATABASE:-sketchfab_data}?authSource=admin
      MONGODB_DATABASE: ${MONGODB_DATABASE:-sketchfab_data}
      MONGODB_TIMEOUT: ${MONGODB_TIMEOUT:-10}
      # Logstash 設定
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000

    volumes:
      - ./logs:/app/logs
    networks:
      - sketchfab-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MongoDB Express 網頁管理介面
  mongo-express:
    image: mongo-express:1.0.2
    container_name: sketchfab-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-admin123}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - sketchfab-network
    profiles:
      - admin

  # Elasticsearch 服務
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: sketchfab-elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=sketchfab-cluster
      - node.name=sketchfab-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - sketchfab-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Logstash 日誌處理服務
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: sketchfab-logstash
    restart: unless-stopped
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/templates:/usr/share/logstash/templates
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - sketchfab-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Kibana 網頁管理介面
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: sketchfab-kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - sketchfab-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

# 網路設定
networks:
  sketchfab-network:
    driver: bridge

# 磁碟區設定
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  elasticsearch_data:
    driver: local
